services:
  chirpstack:
    image: chirpstack/chirpstack:latest  # Build yerine doğrudan imaj kullanıyoruz
    volumes:
      - ./:/chirpstack
    depends_on:
      - postgres
      - redis
      - mosquitto
      - rabbitmq
      - kafka
    environment:
      - DATABASE_URL=postgres://chirpstack_test:chirpstack_test@postgres/chirpstack_test?sslmode=disable
      - REDIS_HOST=redis
      - POSTGRESQL_HOST=postgres
      - MQTT_BROKER_HOST=mosquitto
      - TEST_POSTGRESQL_DSN=postgres://chirpstack_test:chirpstack_test@postgres/chirpstack_test?sslmode=disable
      - TEST_REDIS_URL=redis://redis/1
      - TEST_MOSQUITTO_SERVER=tcp://mosquitto:1884/
      - TEST_KAFKA_BROKER=kafka:9093
      - TEST_AMQP_URL=amqp://guest:guest@rabbitmq:5673
    entrypoint: ["/chirpstack/chirpstack", "--config", "/chirpstack"]
    ports:
      - "9090:8080"
